import React from "react";
import swot1 from "../assets/svg/swot1.svg";
import Image from "next/image";


export default function Privacypolicy() {
  return (
    <div className="bgcontent1">
      <p className="termsh ">Privacy Policy</p>
      <p className="termsp container-md">
        Please go through these terms and conditions carefully as these
        constitute a legal agreement between www.muzztech.com (“Website” or
        “Site”) and you. You must be of legal age (18 years or above) to enter
        into a binding agreement in order to accept the terms. If you do not
        agree to the terms, do not use any of our services/products. By putting
        a check mark next to “I AGREE and clicking on SUBMIT on
        creating/registration of your account or using the services, you
        represent that you have read and agree to the terms and conditions of
        this agreement. <br /><br />This document/agreement is an electronic record in terms
        of Information Technology Act, 2000 and generated by a computer system
        and does not require any physical or digital signatures. This document
        is published in accordance with the provisions of Rule 3 of the
        Information Technology (Intermediaries guidelines) 2011, that provides
        for the due diligence to be exercised by the Site.<br /><br /> MUZZTECH’s Services
        is bound by regulatory norms of the Telecom Regulatory Authority of
        India (TRAI), Department Of Telecommunication of the Govt. of India
        (DOT) and other authorities. Certain features may be removed depending
        on what the law of land dictates without prior notice.
        <br /><br /> The Site is owned
        by Muzztech Wireless Private Limited (Muzztech) and by accessing and
        using it you are indicating that you accept, and agree to comply with,
        these Terms. The terms “you” and “your” for purposes of these Terms,
        means both you in your individual capacity, and the company or other
        business entity whom you represent and on whose behalf you use the site
        under actual or apparent authority. By agreeing to these Terms and/or
        using the site, you represent and warrant that you have the authority to
        represent and legally bind the company or other business entity for whom
        you are acting. If you do not have such authority, you are solely
        responsible for all acts and omissions relating to your use of the Site.
      </p>
    </div>
  );
}
