import React from "react";

export default function Privacypolicy() {
  return (
    <div
      className="container py-5 mt-5 px-3 rounded mb-4"
      style={{
        backgroundColor: "#EAE3D6",
        maxWidth: "800px",
      
        overflowY: "auto", // Ensure scroll if content overflows
        zIndex: 1,
        boxShadow: "0 4px 8px rgba(0,0,0,0.1)", // Added subtle shadow for visual appeal
      }}
    >
      <h1 className="display-4 font-weight-bold mb-3 ">Privacy Policy</h1>
      <p className=" mb-4 ">Last Update: October 20, 2024</p>
      <p
        className="text-dark text-justify lead"
        style={{
          fontSize: "0.875rem", // Reduced font size for compactness
          lineHeight: "1.6", // Increased line height for better readability
        }}
      >
        Please go through these <span className="text-primary">terms</span> and{" "}
        <span className="text-primary">conditions</span> carefully as these
        constitute a legal agreement between www.muzztech.com (“Website” or
        “Site”) and you. You must be of legal age (18 years or above) to enter
        into a binding agreement in order to accept the terms. If you do not agree
        to the terms, do not use any of our services/products. By putting a check
        mark next to “I AGREE” and clicking on SUBMIT on creating/registration of
        your account or using the services, you represent that you have read and
        agree to the terms and conditions of this agreement.
        <br />
        <br />
        This document/agreement is an electronic record in terms of Information
        Technology Act, 2000 and generated by a computer system and does not require
        any physical or digital signatures. This document is published in accordance
        with the provisions of Rule 3 of the Information Technology (Intermediaries
        guidelines) 2011, that provides for the due diligence to be exercised by the
        Site.
        <br />
        <br />
        MUZZTECH’s Services are bound by regulatory norms of the Telecom Regulatory
        Authority of India (TRAI), Department Of Telecommunication of the Govt. of
        India (DOT), and other authorities. Certain features may be removed depending
        on what the law of the land dictates without prior notice.
        <br />
        <br />
        The Site is owned by Muzztech Wireless Private Limited (Muzztech), and by
        accessing and using it, you are indicating that you accept, and agree to
        comply with, these Terms. The terms “you” and “your” for purposes of these
        Terms, mean both you in your individual capacity, and the company or other
        business entity whom you represent and on whose behalf you use the site under
        actual or apparent authority. By agreeing to these Terms and/or using the site,
        you represent and warrant that you have the authority to represent and legally
        bind the company or other business entity for whom you are acting. If you do not
        have such authority, you are solely responsible for all acts and omissions relating
        to your use of the Site.
      </p>
    </div>
  );
}
